### ISSUE TITLE
Trying to download: not found

### ISSUE THREAD

**Issue by annadane** [flathub/com.jagex.RuneScape#102]
anna@debian:~$ flatpak install flathub com.jagex.RuneScape
Looking for matches…

com.jagex.RuneScape permissions:
    ipc           network     pulseaudio     x11     devices
    tags [1]

    [1] proprietary

        ID                           Arch            Branch          Remote          Download
 1. [✗] com.jagex.RuneScape          x86_64          stable          flathub         1.0 kB / 13.5 MB

Error: While downloading https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.5_amd64.deb: Server returned status 404: Not Found
error: Failed to install com.jagex.RuneScape: While downloading https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.5_amd64.deb: Server returned status 404: Not Found

**Comment by marcthe12** [comment]
Jagex keeps screwing checksum every week. See #23.
There is an automated mechanism that updates the checksum although I am not sure how frequently it runs. Should be fixed soon

**Comment by Garbee** [comment]
It checks hourly. This isn't the checksum though, it looks like they moved the file itself (which I should still see a PR that the content size changed.) I'll go pop open a new debian build from the site and see where it is now.

**Comment by Garbee** [comment]
#103 fixes this instance. Problem is it looks like Jagex is finally learning how to do linux distribution right. They're updating the launcher version as they patch things. So I'll look at automating that check a bit more if I can this weekend.
